name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./클라우드\ 실전\ 미니프로젝트/BackEnd/backend/gradlew

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./클라우드 실전 미니프로젝트/BackEnd/backend
          file: ./클라우드 실전 미니프로젝트/BackEnd/backend/Dockerfile
          push: true
          platforms: linux/arm64
          tags: zlxldgus123/spring-app:latest
